/*
 * gen_vectors - write tpvec.h, the inputs and expected outputs for
 * tpbench, computed on the host with the full BearSSL. The transputer
 * build has no 64-bit integers, so it can't hash with SHA-384 or sign;
 * it gets the hash values and signatures ready-made.
 */
#include <stdio.h>
#include <string.h>
#include "bearssl.h"
#include "../rsa_moduli.h"

static void arr(const char *name, const unsigned char *p, size_t n)
{
	size_t i;

	printf("static const unsigned char %s[%lu] = {", name, (unsigned long)n);
	for (i = 0; i < n; i++)
		printf("%s0x%02x,", i % 12 ? " " : "\n\t", p[i]);
	printf("\n};\n");
}

static size_t unhex(unsigned char *dst, const char *src)
{
	size_t n = 0;
	int hi = -1;

	for (; *src; src++) {
		int c = *src, v;

		if (c >= '0' && c <= '9') v = c - '0';
		else if (c >= 'a' && c <= 'f') v = c - 'a' + 10;
		else if (c >= 'A' && c <= 'F') v = c - 'A' + 10;
		else continue;
		if (hi < 0) hi = v;
		else { dst[n++] = (unsigned char)(hi << 4 | v); hi = -1; }
	}
	return n;
}

static void ecdsa(const char *tag, int curve, const br_ec_impl *impl,
	const br_hash_class *hf, size_t hlen)
{
	unsigned char skx[48], hash[64], sig[160], kbuf[BR_EC_KBUF_PUB_MAX_SIZE];
	br_ec_private_key sk;
	br_ec_public_key pk;
	const br_hash_class *ctx = 0;
	br_hash_compat_context hc;
	size_t i, siglen;
	char name[64];

	for (i = 0; i < sizeof skx; i++)
		skx[i] = (unsigned char)(0x5a ^ (i * 13));
	skx[0] = 0x21;
	hf->init(&hc.vtable);
	hf->update(&hc.vtable, "certificate", 11);
	hf->out(&hc.vtable, hash);
	(void)ctx;
	sk.curve = curve;
	sk.x = skx;
	sk.xlen = hlen;
	br_ec_compute_pub(impl, &pk, kbuf, &sk);
	siglen = br_ecdsa_i15_sign_asn1(impl, hf, hash, &sk, sig);
	snprintf(name, sizeof name, "%s_q", tag); arr(name, pk.q, pk.qlen);
	snprintf(name, sizeof name, "%s_hash", tag); arr(name, hash, hlen);
	snprintf(name, sizeof name, "%s_sig", tag); arr(name, sig, siglen);
}

int main(void)
{
	unsigned char n[256], x[256], scalar[32], pt[65];
	size_t glen, i;
	const unsigned char *g;
	static const unsigned char e[3] = { 1, 0, 1 };
	br_rsa_public_key pk;

	printf("/* tpvec.h - generated by gen_vectors.c; do not edit */\n");

	/* P-256: scalar times the generator */
	for (i = 0; i < sizeof scalar; i++)
		scalar[i] = (unsigned char)(0x11 + i * 3);
	scalar[0] = 0x3f;
	arr("p256_scalar", scalar, 32);
	g = br_ec_p256_m31.generator(BR_EC_secp256r1, &glen);
	memcpy(pt, g, glen);
	br_ec_p256_m31.mul(pt, glen, scalar, 32, BR_EC_secp256r1);
	arr("p256_expect", pt, glen);

	ecdsa("e256", BR_EC_secp256r1, &br_ec_p256_m31, &br_sha256_vtable, 32);
	ecdsa("e384", BR_EC_secp384r1, &br_ec_prime_i31, &br_sha384_vtable, 48);

	/* RSA-2048 public operation */
	unhex(n, rsa2048_n_hex);
	memset(x, 0x42, sizeof x);
	x[0] = 0x01;
	arr("rsa_n", n, 256);
	arr("rsa_x", x, 256);
	pk.n = n; pk.nlen = 256; pk.e = (unsigned char *)e; pk.elen = 3;
	br_rsa_i31_public(x, 256, &pk);
	arr("rsa_expect", x, 256);
	return 0;
}
