#!/usr/bin/env python3
"""gen_entities.py > html/entities_tab.h

The named character references the browser knows: HTML 4's 252, &apos;,
and the HTML5 names common on real pages (a full HTML5 table is 2231
names, ~25 KB: too much for what it buys on these machines). Names that
HTML5 also accepts without the semicolon are flagged."""
import html.entities as he

extra = """apos NewLine Tab colon comma period lpar rpar excl quest sol num dollar
percnt ast plus equals lowbar lsqb rsqb lcub rcub vert verbar grave bsol
commat check cross star starf hyphen dash ndash mdash hellip nbsp zwnj zwj
lrm rlm bull middot laquo raquo lsaquo rsaquo ldquo rdquo lsquo rsquo
bdquo sbquo trade copy reg deg plusmn times divide frac12 frac14 frac34
larr rarr uarr darr harr rArr lArr hArr uArr dArr euro pound yen cent
sect para shy macr acute cedil uml ordf ordm sup1 sup2 sup3 iexcl iquest
curren brvbar not micro""".split()

names = set(he.name2codepoint) | set(extra)
rows = []
for n in sorted(names):
    v = he.html5.get(n + ";")
    if v is None or len(v) != 1:
        continue          # multi-codepoint entities: not worth it
    legacy = n in he.html5      # the key without ';' exists
    rows.append((n, ord(v), legacy))
rows.sort(key=lambda r: r[0].encode())   # byte order for bsearch (strcmp)
print("/* entities_tab.h - generated by tools/gen_entities.py; do not edit */")
print("#define N_ENTITIES %d" % len(rows))
print("static const struct entity entities[N_ENTITIES] = {")
for n, cp, legacy in rows:
    print('\t{ "%s", 0x%04X, %d },' % (n, cp, 1 if legacy else 0))
print("};")
